apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      name: user-auth
  template:
    metadata:
      name: user-auth
      labels:
        name: user-auth
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
        - name: auth-services
          image: auth
          ports:
            - containerPort: 8080
        - name: user-management-services
          image: user
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: user-auth
spec:
  selector:
    name: mongo
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
    - port: 8080
      targetPort: 8080
      name: auth-services
    - port: 9090
      targetPort: 9090
      name: user-management-services

---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
    - name: curl
      image: auth-services
