apiVersion: v1
kind: Service
metadata:
  name: user-auth
spec:
  selector:
    app: user-auth
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
        - name: user-auth
          image: shabir67/deall_auth
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/deal_user_db
          imagePullPolicy: Always
